function generos(genero){
    let chave = []
    if(genero=="jogadores"){

        return chave = ["LIONEL MESSI" , "KARIM BENZEMA" , "ROBERT LEWANDOWSKY" ,
         "ANDRES INIESTA" , "SERGIO AGUERO" , "CRISTIANO RONALDO" , "THOMAS MULLER" ,
          "NEYMAR JR" , "KEVIN DE BRUYNE" , "ROMELU LUKAKU" , "SADIO MANE" , 
          "MOHAMMED SALAH" , "GERARD PIQUE" , "LUKA MODRIC" , "TONY KROOS" , "MARCELO VIERA" , 
          "ANTONIE GRIEZMMAN" , "LUIS SUAREZ" , "YANNCIK CARRASCO" ,"IAGO ASPHAS" , "FRANKIE DE JONG" ,
           "XAVI HERNANDES" ,"RADAMEL FALCAO" , "SERGIO BUSQUETS" , "SAMUEL ETOO" ,
          "BASTIAN SCHWEISTEIGER" , "ERIC LAMELA" , "ZLATAN IBRAHIMOVIC" ,"ALVARO MORATA" , "KILYAN MBAPPE" ,
           "BERNARDO SILVA" ,"DAVID SILVA" , "BRUNO FERNANDES" , "PAUL POGBA" ,
          "EDSON CAVANI" , "EVER BANEGA" , "FRANCISCO  TOTTI" ,"SAMI NASRI" , "YAYA TOURE" , "JAMIE VARDY" ,
          "MATEO KOVACIC" , "MARC ANDRE TER STEGEN" , "SERGI GNABRY" ,
          "KINGSLEY COMAN" , "RAHEEM STERLING" , "STEVEN GERRARD" ,"ARJEN ROBBEN" , "MIROSLAV KLOSE" , "DANI ALVES"]

     } else if (genero=="paises") {

        return chave = [ "AUSTRALIA" , "NOVA ZELANDIA" , "NAURU" ,"ILHAS VIRGENS BRITANICAS" , "PAPUA NOVA GUINE" ,
         "FIJI" ,"ILHAS MARSHALL" , "ESTADOS UNIDOS" , "CANADA" ,"MEXICO" , "JAMAICA" , "CUBA" ,
        "PORTO RICO" , "COSTA RICA" , "HONDURAS" ,"NICARAGUA" , "HAITI" , "REPUBLICA DOMINICANA" ,
        "COLOMBIA" , "VENEZUELA" , "BOLIVIA" ,"PERU" , "EQUADOR" , "BRASIL" ,
        "ARGENTINA" , "URUGUAI" , "PARAGUIA" ,"CHILE" , "GUIANA" , "GUIANA FRANCESA" ,"SURINAME" , "ANGOLA" ,
         "MOCAMBIQUE" ,"AFRICA DO SUL" , "MADAGASCAR" , "LESOTO" ,
        "TANZANIA" , "ZAMBIA" , "NAMIBIA" ,"RUANGA" , "UGANDA" , "TOGO" ,"SEYCHELLES" , "BURUNDI" , "ETIOPIA" ,
        "SULDAO" , "REPUBLICA CENTRO AFRICANA" , "GABAO" ,
        "CHADE" , "NIGER" , "NIGERIA" ,"LIBERIA" , "EGITO" , "TUNISIA" ,"LIBIA" , "MARROCOS" , "ARGELIA" ,
        "COSTA DO MARFIN" , "CABO VERDE" , "SAO TOME E PRINCIPE" ,
        "GUINE CONACRI" , "GUINE BISSAU" , "GUINE EQUATORIAL" ,"BENIN" , "BURKINA FASO" , "MALI" ,"CAMAROES" ,
         "SENEGAL" , "ZIMBABUE" ,"QUENIA" , "IEMEN" , "JORDANIA" ,
        "ARABIA SAUDITA" , "CATAR" , "EMIRADOS ARABES UNIDOS" ,"KUWAIT" , "OMA" , "ARMENIA" ,"AZERBAJAO" ,
         "BRUNEI" , "BAHREIN" ,"LIBANO" , "CHIPRE" , "IRA" ,
        "IRAO" , "IRAQUE" , "ISRAEL" ,"SIRIA" , "TURQUIA" , "RUSSIA" ,"CHINA" , "JAPAO" , "COREIA DO SUL" ,"COREIA DO NORTE" ,
         "INDONESIA" , "FILIPINAS" ,
        "MALASIA" , "INDIA" , "NEPAL" ,"SRI LANKA" , "BANGLADESH" , "QUIRGUISTAO" ,"TAIJIQUISTAO" , "PAQUISTAO" , "CAZAQUISTAO" ,
        "TURQUEMENISTAO" , "AFEGANISTAO" , "UZBEQUISTAO" ,
        "HONG KONG" , "TAIWAN" , "LAOS" ,"TAILANDIA" , "VIETNA" , "CAMBOJA" ,"MIAMAR" ,
         "PORTUGAL" , "ESPANHA" ,"FRANCA" , "ITALIA" , "GRECIA" ,
        "MONACO" , "VATICANO" , "LUXEMBURGO" ,"ALEMANHA" , "BELGICA" , "PAISES BAIXOS" ,"DINAMARCA" , "SUICA" , "GERGIA" ,
        "INGLATERRA" , "PAIS DE GALES" , "ESCOSIA" ,
        "IRLANDA DO NORTE" , "REPUBLICA DA IRLANDA" , "ISLANDIA" ,"REPUBLICA CHECA" , "POLONIA" , "BIELORRUSSIA" ,"ALBANIA" ,
         "LITUANIA" , "ILHAS FAROE" ,"ESTONIA" , "MONTE NEGRO" , "SAN MARINO" ,
        "HUNGRIA" , "AUSTRIA" , "CROACIA" ,"ESLOVENIA" , "ESLOVAQUIA" , "BULGARIA" ,"LETONIA" , "UCRANIA" ,
         "NORUEGA" ,"SUECIA" , "FINLANDIA" , "MACEDONIA" ,
        "BOSNIA E HERZEGOVINA" , "SERVIA" , "EL SALVADOR" ,"GRANADA" ,
        "REPUBLICA DEMOCRATICA DO CONGO" , "BOTWANA" , "SERRA LEOA" ,"SOMALIA" , "GAMBIA" , "ANDORRA" ,"GILBRALTAR" , "KOSOVO" , "MALTA" ]

     } else if (genero=="animais") {

        return chave = ["DRAGAO DE KOMODO" , "COELHO" , "PORQUINHO DA INDIA" , "GATO" , "GAFANHOTO", 
        "FORMIGA" , "CAVALO" , "GIRAFA" , "ARANHA", "TUBARAO" , "BALEIA" , "RINOCERONTE" , "ZEBRA", 
        "LOUVA DEUS" , "PEIXE BALAO" , "POLVO DE ANEIS AZUIS" , "PALANCA NEGRA GIGANTE" , "CAO" , "ABELHA" , "CARANGUEIJO" ,
        "MIOCA" , "LESMA" , "MOSCA" ,"MOSQUITO" , "BARATA" , "LINCE" ,"TIGRE" , "LEAO" , "SAPO" ,"SALAMADRA" , "JAVALI" ,
         "HAMSTER"] 

    } else if (genero=="animes") {

        return chave = ["WHISTLE" , "YUGIOH" , "MERMAID MELODY" , "MY MELODY" , "ANOTHER" , "INUYASHA" , "DORAEMON" , "FULLMETAL  ALQUIMIST" , "INUYASHA" , "NARUTO" , "BLEACH" , "DRAGONBALL" , "ONE PIECE" , "AKAME GA KILL" , "NANATSU NO TAIZAI" , "KILLING BITES" , "BOKU NO HERO" , "HIGH SCHOOL DXD" , "ABSOLUTE DUE"]
    
    }
}


export default generos